### ISSUE TITLE
Move from PM repository

### ISSUE THREAD

**Issue by VLM-TechEd** [JustOff/add-bookmark-helper#7]
I received the pop-up notice that ABH is now being served directly from Github rather than from the PM repository, but no explanation was offered. Given the current worldwide Internet environment, this raises questions regarding safety and privacy. Would you be kind enough to tell us why this was done?

Thank you.

**Comment by JustOff** [comment]
The move to GitHub was initiated due to the inappropriate behavior of the Pale Moon Add-ons Site administration. The last straw was the unauthorized editing of the description of my extensions, as well as the disabling of some of them without any explanation. This was done in secret, without any notice before or after, and I'm not sure if this was the only change that happened with my extensions.

At the moment, we have managed to reach a fragile compromise that allowed me to implement the migration to GitHub. That is why I refrained from specifying the above reasons directly in the notification window. Unfortunately, the other side is not so tolerant in their statements both on the forum and on the add-ons site.

Otherwise, nothing has changed, I still support all my extensions and plan to continue this in the future.

**Comment by VLM-TechEd** [comment]
Wow, I didn’t realize there was such conflict with extension developers. Most unfortunate, though honestly, not surprising to me. As a customer (a term they despise, for some crazy reason), I have experienced, and watched others experience, some quite awful behavior coming from the PM team. The project is truly a GREAT idea, and I am thankful for it every day. Still, they often don’t put their “best foot forward”, so to speak.

 

Have a great day, and thank you for responding so honestly and promptly.

 

Kind regards,

Elchanan, for Vibrant Living Ministries
